#!/bin/bash

# Script to rebuild SPIR-V shaders from GLSL source files
# This script compiles GLSL shaders and updates the shader bytecode in the engine

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHADERS_DIR="${SCRIPT_DIR}/shaders"
ENGINE_SHADERS="${SCRIPT_DIR}/../src/internal/shaders.c"

# Check if glslc is available
if ! command -v glslc &> /dev/null; then
    echo "Error: glslc not found. Please install the Vulkan SDK."
    echo "On macOS: brew install vulkan-headers vulkan-loader vulkan-tools"
    exit 1
fi

echo "Compiling shaders..."

# Compile vertex shader
VERT_SRC="${SHADERS_DIR}/shader.vert"
VERT_SPV="${SHADERS_DIR}/shader.vert.spv"
if [ ! -f "${VERT_SRC}" ]; then
    echo "Error: Vertex shader source not found: ${VERT_SRC}"
    exit 1
fi

glslc "${VERT_SRC}" -o "${VERT_SPV}"
echo "  ✓ Compiled ${VERT_SRC} -> ${VERT_SPV}"

# Compile fragment shader
FRAG_SRC="${SHADERS_DIR}/shader.frag"
FRAG_SPV="${SHADERS_DIR}/shader.frag.spv"
if [ ! -f "${FRAG_SRC}" ]; then
    echo "Error: Fragment shader source not found: ${FRAG_SRC}"
    exit 1
fi

glslc "${FRAG_SRC}" -o "${FRAG_SPV}"
echo "  ✓ Compiled ${FRAG_SRC} -> ${FRAG_SPV}"

# Convert SPIR-V to C array format
echo ""
echo "Converting SPIR-V to C arrays..."

# Generate new shaders.c content
{
    cat << 'EOF'
/*
  Copyright 2025 Osfabias

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  @file src/internal/shaders.c
  @brief Embedded shader code implementation
  @author Ilya Buravov (ilburale@gmail.com)
  @details SPIR-V bytecode generated from GLSL shaders for triangle rendering.
           This file is auto-generated by example/rebuild_shaders.sh
           DO NOT EDIT MANUALLY - edit the GLSL source files in example/shaders/ instead.
*/

#include "src/internal/shaders.h"

/*
  Vertex shader SPIR-V bytecode.
  Source: example/shaders/shader.vert
*/
EOF
    
    # Convert vertex shader using Python
    python3 << PYTHON_SCRIPT
import struct
import os

spv_file = "${VERT_SPV}"
with open(spv_file, 'rb') as f:
    data = f.read()

# Read as uint32 words (little-endian)
words = []
for i in range(0, len(data), 4):
    if i + 4 <= len(data):
        word = struct.unpack('<I', data[i:i+4])[0]
        words.append(word)

# Format as C array
print("const uint32_t moss__vert_shader_spv[] = {")
for i in range(0, len(words), 8):
    line_words = words[i:i+8]
    line = "  " + ", ".join(f"0x{w:08x}" for w in line_words)
    if i + 8 < len(words):
        line += ","
    print(line)
print("};")
print("")
print("const size_t moss__vert_shader_spv_size = sizeof(moss__vert_shader_spv);")
PYTHON_SCRIPT

    cat << 'EOF'

/*
  Fragment shader SPIR-V bytecode.
  Source: example/shaders/shader.frag
*/
EOF
    
    # Convert fragment shader using Python
    python3 << PYTHON_SCRIPT
import struct
import os

spv_file = "${FRAG_SPV}"
with open(spv_file, 'rb') as f:
    data = f.read()

# Read as uint32 words (little-endian)
words = []
for i in range(0, len(data), 4):
    if i + 4 <= len(data):
        word = struct.unpack('<I', data[i:i+4])[0]
        words.append(word)

# Format as C array
print("const uint32_t moss__frag_shader_spv[] = {")
for i in range(0, len(words), 8):
    line_words = words[i:i+8]
    line = "  " + ", ".join(f"0x{w:08x}" for w in line_words)
    if i + 8 < len(words):
        line += ","
    print(line)
print("};")
print("")
print("const size_t moss__frag_shader_spv_size = sizeof(moss__frag_shader_spv);")
PYTHON_SCRIPT

} > "${ENGINE_SHADERS}.tmp"

# Replace the old file
mv "${ENGINE_SHADERS}.tmp" "${ENGINE_SHADERS}"

echo "  ✓ Updated ${ENGINE_SHADERS}"
echo ""
echo "Shader rebuild complete!"
